### ISSUE TITLE
`make install-for-dev` is failing to install python modules

### ISSUE THREAD

**Issue by Ahmad-Wahid** [SeitaBV/flexmeasures-openweathermap#14]
I tried to install the plugin for development using `make`, and I had this below issue which is not able to install some dependencies.

```
pip-compile -o requirements/test.txt requirements/test.in
  ERROR: Cannot install -r requirements/test.in (line 8) because these package versions have conflicting dependencies.
Traceback (most recent call last):
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 316, in _backjump
    name, candidate = broken_state.mapping.popitem()
KeyError: 'dictionary is empty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 434, in resolve
    success = self._backjump(causes)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in _backjump
    raise ResolutionImpossible(causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('redis<4.4'), parent=LinkCandidate('https://files.pythonhosted.org/packages/6b/d1/05dcf84b58ad53ac21e17fc48045f1932a39ef3b41f115013e44abac2f8e/fakeredis-1.9.1-py3-none-any.whl (from https://pypi.org/simple/fakeredis/) (requires-python:>=3.7,<4.0)'))]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/piptools/scripts/compile.py", line 630, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/home/ubuntu/Projects/Seita/flexmeasures-openweathermap/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
make[1]: *** [Makefile:36: freeze-deps] Error 1
make[1]: Leaving directory '/home/ubuntu/Projects/Seita/flexmeasures-openweathermap'
make: *** [Makefile:17: install-for-dev] Error 2
```

**Comment by Ahmad-Wahid** [comment]
Because of this issue, github actions are also failing.

**Comment by nhoening** [comment]
Let's try `make upgrade-deps` first

**Comment by Ahmad-Wahid** [comment]
this would upgrade the dependencies but my concern is about `install-for-dev`.

**Comment by nhoening** [comment]
Which installs dependencies...

**Comment by Ahmad-Wahid** [comment]
yes.

**Comment by Ahmad-Wahid** [comment]
The issue is raising because of `fakeredis` latest version which is `0.17.0`. If we downgrade it to `0.16.0` then we can close this issue. @
