### ISSUE TITLE
Support building dependencies, or find out which Python versions we support

### ISSUE THREAD

**Issue by nhoening** [SeitaBV/flexmeasures-openweathermap#24]
When trying the make-supported installation, a user reported an error (see below, they say it works neither with Python 3.11 nor 3.9).

However, for me on Python3.10, `make install` works well (in a virtual env).

We might have an issue with requirements here, and maybe different Python versions. This requires a little research.

```
make install
make install-pip-tools
pip3 install -q "pip-tools>=6.2"
make freeze-deps
make install-pip-tools
pip3 install -q "pip-tools>=6.2"
pip-compile -o requirements/app.txt requirements/app.in

error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully
│ exit code: 1
 ─> [29 lines of output]
Package hdf5 was not found in the pkg-config se
Perhaps you should add the directory containing
to the PKG_CONFIG_PATH environment variable
No package 'hdf5' found
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "<pip-setuptools-caller>", line 34, in <
File "/private/var/folders/xq/wbc5yvh91bz8dc7
_populate_hdf5_info(dirstosearch, inc_dirs,
File "/private/var/folders/xq/wbc5yvh91bz8dc7

raise ValueError('did not find HDF5 headers
ValueError: did not find HDF5 headers
reading from setup.cfg...


HDF5_DIR environment variable not set, chec
checking /Users/edgar/include ...
hdf5 headers not found in /Users/edgar/include
checking /usr/local/include ...
hdf5 headers not found in /usr/local/include
checking /sw/include ...
hdf5 headers not found in /sw/include
checking /opt/include ...
hdf5 headers not found in /opt/include
checking /opt/local/include ...
```

**Comment by Ahmad-Wahid** [comment]
I have tried the plugin on both python `3.9` and `3.11`. I wasn't able to replicate it for 3.9 but for 3.11 first I had to install `HDF5` and `libnetcdf-dev`, then I got an error that is like this

    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [8 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/tmp/pip-resolve-x4klz9f1/llvmlite_d213ef6a83a84de783c170c67eaeb38f/setup.py", line 55, in <module>
            _guard_py_ver()
          File "/tmp/pip-resolve-x4klz9f1/llvmlite_d213ef6a83a84de783c170c67eaeb38f/setup.py", line 52, in _guard_py_ver
            raise RuntimeError(msg.format(cur_py, min_py, max_py))
        RuntimeError: Cannot install on Python version 3.11.4; only versions >=3.7,<3.11 are supported.
        [end of output]

**Comment by nhoening** [comment]
got pipeline to work with 3.11 in the new repo now
